AllCops:
  DisabledByDefault: true

  Rails/OutputSafety:
    Enabled: true
    Bundler/InsecureProtocolSource:
    Enabled: true
    Security/Eval:
    Enabled: true
    Security/JSONLoad:
    Enabled: true
    Security/MarshalLoad:
    Enabled: true
    Security/Open:
    Enabled: true
    Security/YAMLLoad:
    Enabled: true